chech build

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -36,16 +36,20 @@ jobs:
           step_exit_code=${PIPESTATUS[0]}
 
           if [ $step_exit_code == 0 ]; then
-              echo "Status=success" >> $GITHUB_ENV
-              echo -e "Work-flow started by ${{github.actor}} has ✅ Passed " > result.txt
-              echo "Result_text=$(cat result.txt)" >> $GITHUB_ENV
+              echo "Status=Succeeded" >> $GITHUB_ENV
+              echo "Status_icon=✅" >> $GITHUB_ENV
+              echo "Maker_status=:white_check_mark:" >> $GITHUB_ENV
+              echo "Status_msg=Passed" >> $GITHUB_ENV
+              echo "Run_log=🎉 Build completed successfully with no errors." >> $GITHUB_ENV
           else
-            echo "Status=failure" >> $GITHUB_ENV
-            echo -e "Work-flow started by ${{github.actor}} has ❌ failed\n ***** Details ***** \nJob: Build" > result.txt
-            cat output.txt >> result.txt
-            echo "Result_text<<EOF" >> $GITHUB_ENV
-            tail -n 20 result.txt >> $GITHUB_ENV
+            echo "Status=Failed" >> $GITHUB_ENV
+            echo "Status_icon=🚨" >> $GITHUB_ENV
+            echo "Status_msg=Failed at 'Build Frontend' step" >> $GITHUB_ENV
+            echo "Maker_status=:x:" >> $GITHUB_ENV
+            echo -e "Run_log<<EOF" >> $GITHUB_ENV
+            tail -n 20 output.txt | jq -Rs . | sed -e 's/^"//' -e 's/"$//' >> $GITHUB_ENV
             echo "EOF" >> $GITHUB_ENV
+            exit "$step_exit_code"
             
             exit ${step_exit_code}
           fi
@@ -58,11 +62,13 @@ jobs:
           if [ $step_exit_code == 0 ]; then
               echo "Status=Succeeded" >> $GITHUB_ENV
               echo "Status_icon=✅" >> $GITHUB_ENV
+              echo "Status_msg=Passed" >> $GITHUB_ENV
               echo "Maker_status=:white_check_mark:" >> $GITHUB_ENV
               echo "Run_log=🎉 Build completed successfully with no errors." >> $GITHUB_ENV
           else
             echo "Status=Failed" >> $GITHUB_ENV
             echo "Status_icon=🚨" >> $GITHUB_ENV
+            echo "Status_msg=Failed at 'Build Frontend' step" >> $GITHUB_ENV
             echo "Maker_status=:x:" >> $GITHUB_ENV
             echo -e "Run_log<<EOF" >> $GITHUB_ENV
             tail -n 20 output.txt | jq -Rs . | sed -e 's/^"//' -e 's/"$//' >> $GITHUB_ENV
@@ -100,7 +106,7 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "mrkdwn",
-                    "text": "*Repo:* <https://github.com/${{ github.repository }}| Link >\n*Initiator's ID:* ${{github.actor}}\n *Status:* ${{env.Maker_status}} ${{env.Status}}"
+                    "text": "*Repo:* <https://github.com/${{ github.repository }}| Link >\n*Initiator's ID:* ${{github.actor}}\n *Status:* ${{env.Maker_status}} ${{env.Status_msg}}"
                   }
                 },
                 {
