Check out

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -28,7 +28,13 @@ jobs:
       - name: build frontend
         id: build_frontend
         run : |
-          echo Message_log=$(docker build ./frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$IMAGE_TAG) >> $GITHUB_ENV
+          set +e # bash should not exit on command failure
+          docker build ./frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$IMAGE_TAG 2>&1 | tee output.txt
+          step_exit_code=$?
+
+          echo "The Exit code is: $step_exit_code"
+
+          set -e
 
       - name: check frontend build
         id: _if_frontend_failed
